### ISSUE TITLE
"Waiting for WASM" on AngryBots demo

### ISSUE THREAD

**Issue by pventuzelo** [Qwokka/Cetus#1]
Hi,

Awesome work you have done ;) really looking forward to the defcon talk video.

I tried CETUS on AngryBots and it's stuck to the "Waiting for WASM" part.
AngryBots demo: https://beta.unity3d.com/jonas/AngryBots/

Also, can you explain how CETUS detect the current instance and memory related to WASM when the page is loaded?

**Comment by Qwokka** [comment]
Hey @pventuzelo , thanks for the comment!

It looks like unfortunately AngryBots is not a WASM game. According to my (admittedly limited) understanding, there are actually two ways Unity3d can build games for the browser. The first is the newer WebAssembly-backed system and second is the older Javascript-based system. In the case of AngryBots they used the older version.

Cetus detects WASM binaries by "hooking" the functions used to instantiate a WASM instance. As of right now this includes **WebAssembly.instantiate()**, **WebAssembly.instantiateStreaming()** and **WebAssembly.Instance()**. The hook function intercepts the WASM binary and memory object, runs the binary through WAIL, then passes the instrumented binary to the actual handler.

You can see how this works in [init.js](https://github.com/Qwokka/Cetus/blob/master/content/init.js)

Thanks!

Jack

**Comment by pventuzelo** [comment]
Oh my bad, you're right, it's not using WebAssembly.
Thanks for the details.

Patrick
