### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Berus008** [Qwokka/Cetus#10]
Can i use with it any  web based game?

**Comment by Qwokka** [comment]
Hey @Berus008,

Cetus will only work with games that are built with WebAssembly. So this won't include flash, java, or pure Javascript games.

A good way to tell if Cetus will work with a game is to load the game with Cetus enabled. If the Cetus window just says "Waiting for WASM" and never moves beyond that, it's probably not a WebAssembly game.

Hope that helps!

Jack
