### ISSUE TITLE
Not working in devtools

### ISSUE THREAD

**Issue by TristonStuart** [Qwokka/Cetus#16]
For some reason, Cetus refuses to search properly when used in dev tools. I get "Searching..." forever.
I got an error from chrome in "updateStringSearchForm" with `const strType = stringData.strType` saying that "stringData.strType" was undefined. I also got an error "Extension Context Invalidated" with 
`window.addEventListener("cetusMsgIn", function(msg) {
    chrome.runtime.sendMessage(msg.detail);
}, false);`

**Comment by cecio** [comment]
Hello.
Could you provide some more details on how to reproduce the problem?
Is the WASM app you are inspecting publicly  accessible? If so could you provide the URL and the steps you are following to get this behavior?
Also, it could help if you provide exact version of the browser you are using.
Thanks,

**Comment by TristonStuart** [comment]
Ya sure!

Google Chrome:
Version 85.0.4183.83 (Official Build) (64-bit)

Windows:
Windows 10 Home 1903 18362.1016

Cetus Version:
Latest (re-installed)

Here is the wasm game I am trying to hack :
https://1v1.lol/

I am trying to do more complicated things but even basic searches aren't working. It was working a few weeks ago but now it just gets stuck on searching. To test it out just wait for the game to load and click on the Aim Trainer Button to get in a private game. I tried searching for my ammo and it just never finishes searching when I have the dev tools version open. If I click on the chrome extension icon itself to open up the chrome extensions background page and cetus works great.

**Comment by TristonStuart** [comment]
I just wanted to note I tried again and it still isn't working but there are no chrome errors in the extensions page anymore.

**Comment by cecio** [comment]
May be I found something: I'm going to make a pull request with a little modification, then we need to wait the review of @Qwokka in order to have it validated. I'm not 100% sure this is going to fix your issue, but may be.

In the meantime, just to let you know: I saw that this WASM contains a tons of strings, so if you start a search with minimum length of 10 or 20, you are going to get thousand of results, and that means that you have to wait a while.
If you are looking for something in particular is better to use the byte sequence search.

**Comment by Qwokka** [comment]
Looking at it I bet the issue @cecio fixed is at fault. Do you mind confirming if it works better now @TristonStuart?

Thanks!

**Comment by TristonStuart** [comment]
Unfortunately, it doesn't fix the issue.
Here are some screenshots from the game :
https://i.imgur.com/8ltisFJ.png
https://i.imgur.com/0oH5zYx.png

As you can see it works fine with the normal extension background page but doesn't work in the chrome dev tools.
Although the results showed up if I completely close devtools and use the extension background page to redo the same search. Also just as a note I am just searching for i32 numbers and I have gotten this to work well before.

**Comment by Qwokka** [comment]
@TristonStuart Thanks for the screenshots! That helped a lot. This appears to only be an issue when the dev tools window is popped out into its own window. I have a hunch where the problem is so I'm going to work on a fix.

In the meantime you _should_ be able to use Cetus normally with any of the "Dock side" settings in Chrome except for "Undock to separate window"

**Comment by TristonStuart** [comment]
thanks for the reply I didn't think that it being undocked may be the issue! hope you can find a fix

**Comment by Qwokka** [comment]
Should be fixed with 8aa41630aa590538fbfba0621bbcfaddb0012262

**Comment by TristonStuart** [comment]
@Qwokka Search doesn't seem to be working at all anymore.

**Comment by Qwokka** [comment]
@TristonStuart I'm having trouble replicating this but I pushed a change that may help.

When you say search doesn't work at all, do you mean from the popup? Or a docked dev tools panel?

On my current set up both work so if you're still having issues I'm curious.

**Comment by TristonStuart** [comment]
@Qwokka Ya it's not working in anything. Just gets stuck on searching. If you have any ideas for how you want me to try and debug this I would be happy too. I know javascript pretty well. I assume for some reason my google chrome is just not communicating between pages. Anyway here is a picture showing off what I mean: https://i.imgur.com/nFCJhe5.png

**Comment by TristonStuart** [comment]
Just wanted to confirm to you that this code executes fine:
`const sendContentMessage = function(type, msgBody) {
    const msg = {
        type: type,
        body: msgBody
    };

    // We do not query currentWindow because a detached dev tools panel may break
    // this assumtion. See issue #16
	chrome.tabs.query({ active: true }, function(tabs) {
		const activeTab = tabs[0];
        try {
            chrome.tabs.sendMessage(activeTab.id, msg);
        }
        catch (e) {
            // TODO Handle tab closed
            return;
        }
	});
};`

I'm a little busy but ill try to see if the tab gets the message.

**Comment by TristonStuart** [comment]
https://i.imgur.com/Wf717Bp.png

**Comment by TristonStuart** [comment]
Well, I think I finally found an error I can help you out with.
Here is the screenshot:
https://i.imgur.com/eH479Zc.png

**Comment by TristonStuart** [comment]
Ok well, it turns out you can't reload your extension without reloading chrome because of how your chrome extension works. Completely closed chrome and boom it works. Lmao such stupid errors. Anyways thanks for the help. Ill close this error and if I run into any more errors ill make a separate issue.
