### ISSUE TITLE
Uncaught (in promise) TypeError: WebAssembly.instantiate() when after hooking FunkyKart demo

### ISSUE THREAD

**Issue by pventuzelo** [Qwokka/Cetus#2]
Hi again,

i was trying CETUS on the [demo](https://www.funkykarts.rocks/demo.html) of the game FunkyKart but i got this error in my console:

![2019-08-31-182914_673x297_scrot](https://user-images.githubusercontent.com/9038181/64066686-41b4da00-cc1d-11e9-8d1c-22a4172a3fa5.png)

**Comment by Qwokka** [comment]
Oops! Should be fixed with 56a1747b6be2f0985c589d99c327f8719b6e410f

Good catch, thanks!

**Comment by pventuzelo** [comment]
it works ;) thx
