### ISSUE TITLE
Default Patch Preventing WASM Execution

### ISSUE THREAD

**Issue by TristonStuart** [Qwokka/Cetus#21]
I was trying to patch in some wasm and I kept running into errors when the game would try to load it. I thought this was to me being terrible at writing wasm but I tried patching the function without changing anything and it still gives me an error. Here is a screenshot of the error: https://i.imgur.com/wGZWODw.png

The function I am trying to patch is function `88266`. It is in this game: https://1v1.lol/

Any help would be appreciated!

**Comment by Qwokka** [comment]
Should be fixed with 24b2ea17a5c2114f0adbc3900ea5a0295fc8184a. Sorry about that!
