### ISSUE TITLE
Cannot read property 'memory' of undefined

### ISSUE THREAD

**Issue by tobilap** [Qwokka/Cetus#24]
Cetus is great. Works fine with the Tank example. Now taking it to a different application I ran into some issue.

When running it Cetus is stuck at waiting for WASM , I assume its because the application doesn't continue loading when Cetus is active.

`Uncaught (in promise) RuntimeError: abort(TypeError: Cannot read property 'memory' of undefined). Build with -s ASSERTIONS=1 for more info.`

Running Chrome 87 and pulled latest version of the plugin.

URL of the application: https://neuz-h5.flyff.com/client/index.html

**Comment by Qwokka** [comment]
Hey @tobilap 

Thanks for reporting this. It should be working now with cd2d931ec2b219e28a6291766124558aa7344561. This fix probably helps support a lot of other games too. Let me know if you still have trouble!

Jack
