### ISSUE TITLE
Uncaught TypeError: Do not know how to serialize a BigInt on Tanks!

### ISSUE THREAD

**Issue by pventuzelo** [Qwokka/Cetus#3]
Hi Jack,

When playing with cetus on Tank!, i triggered an "Uncaught TypeError: Do not know how to serialize a BigInt".

![2019-09-02-095837_446x207_scrot](https://user-images.githubusercontent.com/9038181/64098958-6b2e4c80-cd68-11e9-9c2d-372712f11d93.png)

Reproduction: 
* go on http://webassembly.org.cn/demo/Tanks/
* search for 1000 / EQ / i64
* crash happened

**Comment by Qwokka** [comment]
Sorry for the delay, this turned out to be a bigger issue than I expected.

This and a host of other BigInt related issues should be fixed with c02f59ff1fa65be18ec8c0cb3ad417bc00adee24

Thanks again for reporting this!

**Comment by pventuzelo** [comment]
Good thanks ;)
