### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by JackieWeiss** [Qwokka/Cetus#30]
With Cetus enabled the error gets thrown and the game gets stuck on the loading screen and never fully starts. Game works fine without Cetus.
Using Chromium and tested with both the 1.02 version and the master version.
[Game](https://games.nakamoto.games/free/alien-apocalypse/)

**Comment by Qwokka** [comment]
Hi @JackieWeiss 

This appears to be fixed with 292178c5c3cfb73d18e41b536765e522d5b0d426 and a067515a4cd27ab9f50331b2e8a19c41e2a9f8a2

Thanks for the report!
