### ISSUE TITLE
Speed Hack values

### ISSUE THREAD

**Issue by vlassev** [Qwokka/Cetus#31]
Hi, it is possible to put some speed values between 0 and 1 for slowing down the game?
Thanks!

**Comment by Qwokka** [comment]
Hey @vlassev 

You can set the speedhack to any arbitrary speed by setting the variable `cetus.speedhack.multiplier` from the Javascript console. For example, you can set the speed to .5 with this command:

```js
cetus.speedhack.multiplier  = 0.5
```

Let me know if you have any trouble!

**Comment by vlassev** [comment]
It works perfect!
Many Thanks!!!
