### ISSUE TITLE
waiting for wasm

### ISSUE THREAD

**Issue by zorelix** [Qwokka/Cetus#33]
always waiting for WASM i install it correctly but i cant use it

**Comment by Qwokka** [comment]
Hi @zorelix 

Can you give an example of a game that you're trying to use Cetus with?

Jack

**Comment by zorelix** [comment]
gala games

**Comment by zorelix** [comment]
what game does the program work? only unity based games?

**Comment by Qwokka** [comment]
Cetus _should_ work on any in-browser games that use WebAssembly. I'm not familiar with Gala Games so I'll take some time to see if it qualifies.

If Gala Games uses WebAssembly and Cetus isn't working with them, that's a bug and I'll do my best to fix it.

Jack

**Comment by zorelix** [comment]
the game was called Town Star idk if its running or not with webassembly is there a way to check if the game is running with WebAssembly?

**Comment by Qwokka** [comment]
I just took a look. Town Star is definitely a WebAssembly game so this is a bug. I'm going to tag this issue as a bug and try to fix it ASAP.

Thanks for bringing this to my attention!

Jack

**Comment by Qwokka** [comment]
This should be fixed with cc25cb81ed37b09e7b4b8b7efb05938d81e1d7a8 but I'll let you give it a shot before I close this.

Jack
