### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'buffer')

### ISSUE THREAD

**Issue by BoomBoomMushroom** [Qwokka/Cetus#37]
After trying to search for the value 100 I get this error in the extentions
I am using Opera GX and I have tried this in Chrome
The search also never ends

When I add the extension I get this error:
```
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
"manifest_version": 2,
```

Console error when I search:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'buffer')
    at Cetus.memory (cetus.js:51:44)
    at Cetus.search (cetus.js:146:29)
    at cetus.js:505:34
memory @ cetus.js:51
search @ cetus.js:146
(anonymous) @ cetus.js:505
```

Extention Error:

Context
https://primerlearning.org/
Stack Trace
content/cetus.js:51 (memory)
content/cetus.js:146 (search)
content/cetus.js:505 (anonymous function)

```
memory(type) {
    const memType = this.getMemoryType(type);

    // We return a new object each time because the WebAssembly.Memory object
    // will detach if it is resized
    return new memType(this._memObject.buffer);
}
```

**Comment by Qwokka** [comment]
Hi @BoomBoomMushroom 

I think this is fixed now with 247a5ae28b9b39163ce3b8e2a4115be058c68d50. Please let me know if you still have issues.

Thanks!
Jack
