### ISSUE TITLE
Cetus crashes Unity startup

### ISSUE THREAD

**Issue by hidotp** [Qwokka/Cetus#39]
When I try to start a WebGL Game made with Unity it keeps it stuck at 95% in loading screen and this error:
![image](https://user-images.githubusercontent.com/38942179/165101740-dd8cb86f-3308-4647-b34f-8d6b0bb8cf5b.png)

Upon startup I also get this error: 
![image](https://user-images.githubusercontent.com/38942179/165101995-5f4c16fe-ff66-4ae4-a566-5827f1874e7a.png)

Using the newest version of the Chrome dev browser and Cetus version 1.3 and Cetus is my only extension

**Comment by hidotp** [comment]
![image](https://user-images.githubusercontent.com/38942179/165166509-80509b4a-6db0-4bad-85d0-c64b84de2118.png)
And this one intercepts

**Comment by Qwokka** [comment]
Hey @hidotp 

I think this is fixed with cd7e42f0b6e9ad0ddd6f796b543017140409173a. Can you give it a shot and let me know if you're still having issues? Thanks!

Jack

**Comment by hidotp** [comment]
Works now thank you!
