### ISSUE TITLE
Cannot enlarge memory arrays. / Out of memory

### ISSUE THREAD

**Issue by fruitf** [Qwokka/Cetus#4]
When attempting to follow along with the demo or DEFCON talk, Web-Assembly aborts due to running out of memory. 
```
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 50331648, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
```
I have tried to edit je json file's TOTAL_MEMORY using BurpSuite, although I have had no results. 
This happens on both Firefox 73.0b5 (64-bit) & Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

**Comment by Qwokka** [comment]
Hey @fruitf, thanks for the report! I'm investigating it now. I haven't been able to replicate the problem yet so do you mind answering a couple questions to help me out?

First off, are you using the WASM demo at https://wasm.bootcss.com/demo/Tanks/ or another game?

Secondly, does this problem go away when Cetus isn't installed?

Thanks!

Jack

**Comment by fruitf** [comment]
Hey @Qwokka! Sorry for the late reply, I can no longer replicate the problem, now instead the game always runs out of memory for me. I'm sorry to have wasted your time. I'll remake a ticket once I can replicate this. 

Yes, I am using the WASM demo at https://www.wasm.com.cn/demo/Tanks/. 
Although I have encountered different problems with other games.

Thank you and again sorry!
