### ISSUE TITLE
Wait for WASM - Flyff Universe

### ISSUE THREAD

**Issue by xzeroun** [Qwokka/Cetus#41]
Whenever I try to open up Cetus with flyff universe open, it keeps giving me the Waiting for WASM message. I'm fairly confident this is a WASM game according to the dev tools. Please let me know if it is just something I am doing wrong as I'd love to utilize this. Thanks!

https://i.imgur.com/lXuOo2V.png

https://universe.flyff.com/play

**Comment by Qwokka** [comment]
Hey @xzeroun 

Thanks for providing so much information with your issue!

Could you try with the latest release that I just pushed? https://github.com/Qwokka/Cetus/releases/tag/v1.03

Flyff is working for me with this latest version, so hopefully it'll work for you as well.

Thanks!
Jack

**Comment by xzeroun** [comment]
Yep, it now works. Time to learn how to use this now :). Thanks!!!

**Comment by johmarjac** [comment]
I have same issue, Wait For WASM, with v1.03.1

**Comment by Qwokka** [comment]
Hi @xzeroun ,

Sorry I didn't see your message earlier. Github doesn't alert that comments have been edited so I never got a notification. I'm able to do a handful of things such as locating my X,Y,Z coordinates and modifying them. What specifically are you having trouble with?

**Comment by Qwokka** [comment]
Hi @johmarjac 

I'm testing this right now and it seems to work fine. Do you have any errors in your browser console when you run the game with Cetus installed?

**Comment by k0gasa** [comment]
Can confirm, working well on my end as well
