### ISSUE TITLE
Question: How to call functions?

### ISSUE THREAD

**Issue by testitm** [Qwokka/Cetus#43]
Can Cetus not just patch functions, but call them too?
Also, are there any chances to trace function calls?

**Comment by Qwokka** [comment]
Hey @testitm 

Cetus doesn't support those features, but they are pretty easy to implement using the underlying WASM modification library, [WAIL](https://github.com/Qwokka/WAIL).

I created a couple examples. This first one demonstrates exporting an internal function so it can be called arbitrarily:

https://gist.github.com/Qwokka/c1990823c24a801332da12d103ef9a0a

The second demonstrates basic function tracing by injecting a Javascript callback into the start of every function:

https://gist.github.com/Qwokka/027e34d85d86dbe9759c5ce945866bd5

I believe these could both be implemented pretty easily as Greasemonkey scripts so you can run them on any script you want.

Hope that helps, let me know if you have other questions!
Jack

**Comment by testitm** [comment]
I appreciate it!
