### ISSUE TITLE
Question: can i use pointers with Cetus?

### ISSUE THREAD

**Issue by noorabdo2** [Qwokka/Cetus#44]
Hi I'm playing a  WebAssembly game, i want to change my avatar position i found the addresses I'm searching for and tried to change the value and it worked, but every time i transfer to another room or reloading the game i have to walk through that process again which is kinda boring and time wasting i was using cheat engine so i tried to search for pointers and found it is impossible so is is possible with Cetus ?

**Comment by Qwokka** [comment]
Hi @noorabdo2 

Unfortunately Cetus doesn't support Cheat Engine-style pointer scanning. I think you can get a similar effect (Not having to find an address every time something changes) with a process like this:

1. Find the address of your coordinates
2. Set a *read* watchpoint on this address
3. Take note of the function and instruction that triggers the watchpoint

Then to find the address again:

1. Place a breakpoint on the function and instruction from earlier using the browser debugger
2. Trigger the breakpoint and find the new address on the stack

Does that seem like it might do what you're looking for?

**Comment by noorabdo2** [comment]
Hi thanks for responding, i can do the 3 first steps
i got the function and instructions here
wasm-function[28607]:20450423

```
get_local 0
i32.const 2047
i32.and 
i32.const 70982
i32.add 
call_indirect 18 0
end 
```
but I'm not familiar with browser debugger tool and still newbie at this

Can you explain the last two steps in more detail, thank you very much.

**Comment by Qwokka** [comment]
Are you sure that's the instruction that's triggering the read watchpoint? There doesn't seem to be a memory load there. If you can find the instructions triggering the watchpoint I'll put together a more detailed example.

Alternatively, if you're comfortable sharing the game you're looking at I can give it a shot.

**Comment by noorabdo2** [comment]
Thank you very much, it's just a game I used to play in my childhood
it's name is woozworld i'm looking for XZ value type f32 
there's 6 addresses for player X and another 6 for player Z there's no addresses for Y because it's 2D 
like this : https://ibb.co/dQySLP1


to actually change the player X or Z i tried to change only 1 address  and it doesn't worked i had to change 2 Addresses values to actually make it work

**Comment by Qwokka** [comment]
Hi @noorabdo2 

Sorry for the delay, I spent a bit more time on this than I expected. Long story short, this was a good excuse for me to implement something I've been meaning to do for a long time - adding features to Cetus patches.

So with that in mind, I think I've got a decent solution for you. First off, you'll need to install the latest git version of Cetus by running this command:

`git clone --recursive https://github.com/Qwokka/Cetus`

Then you can install this patch I put together:

```.json
{
    "name": "Test Patch V2",
    "version": "1.1",
    "url": "client.woozworld.com/game/11.7.1/release/index.html",
    "functionPatches": [],
    "callbacks": {
        "processor": "const typeEntry = processor.addTypeEntry({\n    form: 'func',\n    params: ['i32'],\n});\n\nconst importEntry = processor.addImportEntry({\n    moduleStr: 'env',\n    fieldStr: 'woozCoordCallback',\n    kind: 'func',\n    type: typeEntry,\n});\n\nconst realIndex = processor.getFunctionIndex(47065 - 2);\n\nconst codeElementParser = function(parameters) {\n    const reader = new BufferReader();\n\n    reader.copyBuffer([ OP_GET_LOCAL, 0x00 ]);\n    reader.copyBuffer([ OP_CALL ]);\n    reader.copyBuffer(importEntry.varUint32());\n    reader.copyBuffer([35,7,33,2,35,7,65,16,106,36,7,32,2,32,1,41,2,0,55,3,0,32,2,65,8,106,34,1,32,2,41,2,0,55,2,0,32,0,32,1,41,2,0,55,2,100,32,2,36,7,11]);\n\n    return reader.write();\n}\n\nprocessor.addCodeElementParser(realIndex, codeElementParser);\n",
        "preinstantiate": "importObject.env.woozCoordCallback = function(coords) { cetus.addBookmark(coords + 100, 'f32'); cetus.addBookmark(coords + 104, 'f32'); };"
    }
}
```
You can save that as *patch.json* then import it from the *Import Patches* window. The patch will activate the next time you load the game.

This patch modifies the WASM function 47065 and calls a Javascript function every time the X and Y coordinates are modified. So each time you load the game or load a new level, 2 new bookmarks should be added corresponding to the new X and Y coordinates.

This extended patch feature is experimental (I wrote all the code today) so please let me know if you have issues with it.

Jack

**Comment by noorabdo2** [comment]
When i try to import the patch it doesn't get imported when i click show patches i can't find it there

**Comment by Qwokka** [comment]
Are you using the git version by running the command I posted? The latest release won't have the new features I added to support this.

If you're still having issues with the git version I'll look into it, but it seems to be working for me.

**Comment by noorabdo2** [comment]
Oh it's working, my bad I didn't used the last version. It's working very good too, thanks 🙏
