### ISSUE TITLE
Cetus not working

### ISSUE THREAD

**Issue by therealebraheem** [Qwokka/Cetus#49]
Hello. When I try this step here: Press the "double arrow" button >> and then select Cetus from the list of options nothing happens when i press the double arrows in the console. Do you know the fix?

**Comment by Qwokka** [comment]
Hi @therealebraheem 

Sorry for the delay, I've been taking time away from the computer over the holidays.

When you click on Cetus in the menu, it should open a tab in the browser console. If this isn't working, please check the URL `chrome://extensions`. From there you should see Cetus in the list of extensions. Can you press the red *Errors* button (Assuming it's there) and copy the output here? Thanks!

Jack

**Comment by Qwokka** [comment]
No problem, let me know if you have other issues!

Jack
