### ISSUE TITLE
WailParses is not defined

### ISSUE THREAD

**Issue by fantarics** [Qwokka/Cetus#54]
Any games including:
https://www.wasm.com.cn/demo/Tanks/
https://suragames.com/games/CombatOnline/index.php

are not loading (all of them are stuck on the loading process)

in the tanks console i saw this error log:

![image](https://user-images.githubusercontent.com/66209368/233857751-4306b2fe-b6ca-4f90-9e6e-a68f2cf28e5d.png)

also this in the 2nd game:
![image](https://user-images.githubusercontent.com/66209368/233858159-e6f53582-0893-407b-be39-d911a183c0f9.png)

Are there dependencies i need to download for this error to pass?

**Comment by Qwokka** [comment]
Hi @fantarics ,

If you're running the git version please make sure that you cloned using the following command:

`git clone --recursive https://github.com/Qwokka/Cetus`

Let me know if that doesn't fix it.

Jack

**Comment by fantarics** [comment]
> Hi @fantarics ,
> 
> If you're running the git version please make sure that you cloned using the following command:
> 
> `git clone --recursive https://github.com/Qwokka/Cetus`
> 
> Let me know if that doesn't fix it.
> 
> Jack

![image](https://user-images.githubusercontent.com/66209368/233859039-c9de3c09-457a-4a60-ba46-c8099f5d8eac.png)
I have followed the steps of the Chrome installation, I didn't clone the repo

**Comment by fantarics** [comment]
Could mean nothing, but I used a Source code package, instead of the [Cetus_v1.03.1.zip] 
and i see that the latter has .gitmodules while the one i used didn't could it be the reason?
![image](https://user-images.githubusercontent.com/66209368/233859314-44f4a372-ff9b-498f-bc84-c9d74076bd0e.png)

**Comment by Qwokka** [comment]
That's probably the problem. I should make a note that the *Source Code* link effectively just includes the repo itself (Not the submodules).

If you download from the link `Cetus_v1.03.1.zip` everything should be there. I just double checked to be sure.

Jack

**Comment by fantarics** [comment]
> 

Good to know. thank you. will try and let you know!
