### ISSUE TITLE
Changed / Unchanged filtering

### ISSUE THREAD

**Issue by Riddle1001** [Qwokka/Cetus#55]
In Cheat Engine, you can perform a search for all values and then filter them based on changed or unchanged values. For instance, if you have 105 health points and this information is not displayed, you can do this:

1. Initiate a scan for all values related to the data type you're interested in.
2. Take damage, reducing your health points, for example, to 97.
3. Perform a search for changed values to filter out all values that have been altered since the last scan.
4. Search for unchanged values to narrow down the results further, as you haven't taken any additional damage.
5. Repeat these steps as needed to isolate the value representing your health points.

Would be a nice feature

**Comment by Riddle1001** [comment]
I know there is Differential Search, but this would also be very very nice

**Comment by Qwokka** [comment]
Hi @Riddle1001 

Sorry for the delayed response, it's been a busy week.

This may be a dumb question but I'm having trouble figuring out the difference between this and using the built-in search without a starting value. If I understand correctly, you should be able to follow the same steps this way. Please let me know if I'm mistaken.

Jack

**Comment by Riddle1001** [comment]
Hmm, I could be mistaken, step 4 
"Search for unchanged values to narrow down the results further, as you haven't taken any additional damage."

This is possible with Cetus?

To put it in perspective, if I start with 5 values and I want to see ones that haven't change since my previous scan (let's say 2 of them did change), I can trim down the values to isolate those that remained static. Consequently, I'd be left with 3 values in this case.

**Comment by Qwokka** [comment]
If you're trying to look for values that have/haven't changed you can use the "NE" or "EQ" search terms (respectively). Does that help or am I misunderstanding?

Jack

**Comment by Riddle1001** [comment]
> 

Oh okay, I will try that. Seems like it'd make sense.

**Comment by Riddle1001** [comment]
Seems to be working thanks!
