### ISSUE TITLE
When using Cetus my game slows down.

### ISSUE THREAD

**Issue by Reubinator** [Qwokka/Cetus#56]
When im using cetus on a online multiplayer game my game speed decreases significantly speed hack is disabled. This happens just by having the extension installed and opening the site, in this case 1v1.lol

**Comment by Qwokka** [comment]
Hi @Absurv69 

This is a consequence of the fact that Cetus does a lot of modifications to WASM binaries to make watchpoints function. Unfortunately, this can have a negative effect on performance. Another user made an interesting suggestions in #58 about improving performance when watchpoints are not required. It's difficult to speed up the performance of watchpoints as is though. Sorry about that!

Jack

**Comment by Absurv69** [comment]
> Hi @Absurv69
> 
> This is a consequence of the fact that Cetus does a lot of modifications to WASM binaries to make watchpoints function. Unfortunately, this can have a negative effect on performance. Another user made an interesting suggestions in #58 about improving performance when watchpoints are not required. It's difficult to speed up the performance of watchpoints as is though. Sorry about that!
> 
> Jack

Ah okay, thanks though.

**Comment by Qwokka** [comment]
You should now be able to use Cetus without slowdown by setting the *Enable Watchpoints* option to *None* from the extension options. This will disable watchpoints as a functionality but the slowdown should stop.

Jack
