### ISSUE TITLE
Turn of logging functionality

### ISSUE THREAD

**Issue by Riddle1001** [Qwokka/Cetus#58]
So I patched the game, now is there anyway to make the game run smoother but shutting off other features except the patching?

**Comment by Riddle1001** [comment]
I've commented out code to do it, but I think this would be a nice thing to add.

**Comment by Qwokka** [comment]
Hey @Riddle1001 ,

You mean the logs with the emoji octopus or something else? I can probably make this toggleable but I'm surprised if that's causing noticeable impact to performance. Did commenting those out help make the game smoother?

Jack

**Comment by Qwokka** [comment]
Gotcha, that would definitely speed up the performance! That's a reasonable idea since you're probably not the only person trying to use Cetus without the watchpoint functionality.

Jack

**Comment by Qwokka** [comment]
This is now doable with 678d74dd9cade7ab819ebc6be5c5098e948c8195. From the extension options, you can now set the level of instrumentation to one of the following:

* All watchpoints (default)
* Only read watchpoints
* Only write/freeze watchpoints
* No watchpoints

This should allow users who don't care about the watchpoint functionality to use Cetus without any significant performance impact.

This was a pretty large change internally so there may be some new bugs to work out as a result.

**Comment by Riddle1001** [comment]
Thanks :+1:

**Comment by Riddle1001** [comment]
> This is now doable with [678d74d](https://github.com/Qwokka/Cetus/commit/678d74dd9cade7ab819ebc6be5c5098e948c8195). From the extension options, you can now set the level of instrumentation to one of the following:
> 
> * All watchpoints (default)
> * Only read watchpoints
> * Only write/freeze watchpoints
> * No watchpoints
> 
> This should allow users who don't care about the watchpoint functionality to use Cetus without any significant performance impact.
> 
> This was a pretty large change internally so there may be some new bugs to work out as a result.

Hey, coming back to this after a little while, I tried it and it works fine until I disable the watch points inside the chrome extension options. I already just tried manually commenting out the ` wail.addInstructionParser(OP_I64_LOAD,     readWatchpointInstrCallback);` functions like before as a temp fix and still the same issue.

`/#file-name:1 Uncaught (in promise) CompileError: WebAssembly.instantiate(): Compiling function #54979 failed: function index #110895 is out of bounds @+19973184`
