### ISSUE TITLE
Broken "patch" option in the last release.

### ISSUE THREAD

**Issue by hazyone** [Qwokka/Cetus#65]
Hey :)
I've tested the latest release 1.0.4. And "patch" function not works.
Yeah, you can open some function, you can make editions, you can save them, but patch will be not applied to the bytecode and also if you will download this patch, you fill see only "name", "url" fields, but not the "bytes" one.

btw, version latest -1 works as desired.

Maybe somehow .zip contains another version? bc after unpacking I see in the manifest:
 "version": "1.03", but not the 1.0.4

**Comment by Qwokka** [comment]
Hey @hazyone ,

Sorry for the trouble, this should be fixed with 458976b33a6f02383b83eb5838b43aa97bcb310f . I changed the format of patch files to add some new features but I still haven't worked out all the kinks. Still, this was a dumb mistake on my part so thanks for catching it!

Jack
