### ISSUE TITLE
Speed Hack

### ISSUE THREAD

**Issue by R3dow** [Qwokka/Cetus#74]
So im new at this and i cant change the speed to more than 10x i woul like to change it as much as i want and i saw a isse with slowing it down i should write cetus.speed.multiplier = 0.5 but that doesnt work it doesnt slow it down t just says an error: Uncaught TypeError: Cannot read properties of null (reading 'speed')
    at <anonymous>:1:7

so if anyone can help me i appreciate it!

**Comment by Qwokka** [comment]
Hey @R3dow , can you try this?

```
cetus.speedhack.multiplier = 0.5
```
